const mockPDFs: PDF[] = [
  {
    id: "1",
    title: "Introduction to Algorithms",
    description:
      "Comprehensive guide to data structures and algorithms for computer science students.",
    subject: "Computer Science",
    authors: ["John Doe", "Jane Smith"],
    tags: ["Textbook", "Algorithms", "Data Structures"],
    uploadDate: "2024-01-15",
    progress: 65,
    uploader: "Dr. Adebayo Johnson",
    thumbnail: "/images/calculus-mathematics-notes.png",
    fileSize: "15.2 MB",
    downloads: 1250,
    likes: 89,
    isPublic: true,
  },
  {
    id: "2",
    title: "Calculus I Lecture Notes",
    description:
      "Complete lecture notes covering limits, derivatives, and integration.",
    subject: "Mathematics",
    tags: ["Lecture Notes", "Calculus", "Mathematics"],
    uploadDate: "2024-01-10",
    authors: ["John Doe", "Jane Smith"],
    uploader: "Prof. Fatima Okafor",
    thumbnail: "/images/algorithms-textbook-cover.png",
    fileSize: "8.7 MB",
    downloads: 890,
    progress: 23,
    likes: 67,
    isPublic: true,
  },
  {
    id: "3",
    title: "Organic Chemistry Past Questions",
    description:
      "2020-2023 past examination questions with detailed solutions.",
    subject: "Chemistry",
    tags: ["Past Questions", "Organic Chemistry", "Exam Prep"],
    uploadDate: "2024-01-08",
    authors: ["John Doe", "Jane Smith"],
    uploader: "Dr. Emeka Nwankwo",
    thumbnail: "/images/chemistry-past-questions-exam.png",
    fileSize: "12.4 MB",
    downloads: 2100,
    progress: 89,
    likes: 156,
    isPublic: true,
  },
  {
    id: "4",
    title: "Physics Laboratory Manual",
    description:
      "Comprehensive laboratory experiments and procedures for Physics 101.",
    subject: "Physics",
    tags: ["Laboratory", "Physics", "Experiments"],
    uploadDate: "2024-01-05",
    authors: ["John Doe", "Jane Smith"],
    uploader: "Dr. Kemi Adeyemi",
    thumbnail: "/images/physics-laboratory-manual-experiments.png",
    fileSize: "6.8 MB",
    downloads: 567,
    progress: 45,
    likes: 43,
    isPublic: true,
  },
  {
    id: "5",
    title: "Nigerian Literature Anthology",
    description: "Collection of works by prominent Nigerian authors and poets.",
    subject: "Literature",
    authors: ["John Doe", "Jane Smith"],
    tags: ["Literature", "Nigerian Authors", "Anthology"],
    uploadDate: "2024-01-03",
    uploader: "Prof. Chinua Achebe Jr.",
    thumbnail: "/images/nigerian-literature-anthology-books.png",
    fileSize: "18.9 MB",
    progress: 78,
    downloads: 734,
    likes: 92,
    isPublic: true,
  },
  {
    id: "6",
    title: "Microeconomics Study Guide",
    description:
      "Essential concepts and practice problems for microeconomics course.",
    subject: "Economics",
    tags: ["Study Guide", "Microeconomics", "Practice Problems"],
    uploadDate: "2024-01-01",
    uploader: "Dr. Amina Hassan",
    thumbnail: "/images/microeconomics-study-guide-textbook.png",
    fileSize: "9.3 MB",
    downloads: 445,
    likes: 38,
    isPublic: true,
    authors: ["Matt Haig"],
    progress: 65,
  },
];

const user = {
  avatar: "/",
  name: "John Doe",
  role: "",
  email: "john.doe@example.com",
};

const badgeColor: { [key: string]: string } = {
  "Computer Science": "#312e81",
  Mathematics: "#1e293b",
  Physics: "#f59e0b",
  Chemistry: "#64748b",
  Biology: "#0d9488",
  Engineering: "#1e40af",
  Economics: "#06b6d4",
  Literature: "#166534",
  history: "#84cc16",
  Psychology: "#991b1b",
};

const mockPDF: PDFDocument = {
  id: "1",
  title: "Introduction to Algorithms",
  description:
    "Comprehensive guide to data structures and algorithms for computer science students.",
  subject: "Computer Science",
  tags: ["Textbook", "Algorithms", "Data Structures"],
  uploadDate: "2024-01-15",
  uploader: "Dr. Adebayo Johnson",
  fileUrl: "/sample.pdf", // This would be a real PDF URL
  fileSize: "15.2 MB",
  downloads: 1250,
  likes: 89,
  pages: 1312,
};

const chartData: ChartData[] = [
  {
    month: "Jan",
    averageReadingTime: 320,
    downloads: 1500,
    searchQueries: 4500,
  },
  {
    month: "Feb",
    averageReadingTime: 285,
    downloads: 1350,
    searchQueries: 4200,
  },
  {
    month: "Mar",
    averageReadingTime: 340,
    downloads: 1600,
    searchQueries: 4800,
  },
  {
    month: "Apr",
    averageReadingTime: 310,
    downloads: 1450,
    searchQueries: 4600,
  },
  {
    month: "May",
    averageReadingTime: 360,
    downloads: 1700,
    searchQueries: 5000,
  },
  {
    month: "Jun",
    averageReadingTime: 330,
    downloads: 1550,
    searchQueries: 4700,
  },
  {
    month: "Jul",
    averageReadingTime: 350,
    downloads: 1650,
    searchQueries: 4900,
  },
  {
    month: "Aug",
    averageReadingTime: 300,
    downloads: 1400,
    searchQueries: 4300,
  },
  {
    month: "Sep",
    averageReadingTime: 370,
    downloads: 1750,
    searchQueries: 5100,
  },
  {
    month: "Oct",
    averageReadingTime: 325,
    downloads: 1520,
    searchQueries: 4600,
  },
  {
    month: "Nov",
    averageReadingTime: 345,
    downloads: 1680,
    searchQueries: 4800,
  },
  {
    month: "Dec",
    averageReadingTime: 315,
    downloads: 1480,
    searchQueries: 4400,
  },
];

const feedDataSet: FeedData[] = [
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T12:00:00Z",
    src: "user1@example.com",
    name: "Alice Johnson",
    role: "Editor",
    action: "Published",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T12:15:00Z",
    src: "user2@example.com",
    name: "Bob Smith",
    role: "Reviewer",
    action: "Reviewed",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T12:30:00Z",
    src: "user3@example.com",
    name: "Charlie Brown",
    role: "Author",
    action: "Created",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T12:45:00Z",
    src: "user4@example.com",
    name: "Dana Lee",
    role: "Admin",
    action: "Approved",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T13:00:00Z",
    src: "user5@example.com",
    name: "Eve Wilson",
    role: "Editor",
    action: "Edited",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T13:15:00Z",
    src: "user6@example.com",
    name: "Frank Davis",
    role: "Reviewer",
    action: "Commented",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T13:30:00Z",
    src: "user7@example.com",
    name: "Grace Kim",
    role: "Author",
    action: "Drafted",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T13:45:00Z",
    src: "user8@example.com",
    name: "Hank Taylor",
    role: "Admin",
    action: "Deleted",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T14:00:00Z",
    src: "user9@example.com",
    name: "Ivy Clark",
    role: "Editor",
    action: "Updated",
  },
  {
    link: "/images/woman.jpg",
    time: "2025-09-08T14:15:00Z",
    src: "user10@example.com",
    name: "Jack Moore",
    role: "Reviewer",
    action: "Scheduled",
  },
];

const feedData: FeedData[] = [
  {
    link: "/images/avatar1.png",
    time: "2025-09-08T12:00:00Z",
    src: "user1@example.com",
    name: "Alice Johnson",
    role: "Editor",
    action: "Published",
  },
  {
    link: "/images/avatar2.png",
    time: "2025-08-08T12:15:00Z",
    src: "user2@example.com",
    name: "Bob Smith",
    role: "Reviewer",
    action: "Reviewed",
  },
  {
    link: "/images/avatar1.png",
    time: "2025-07-08T12:30:00Z",
    src: "user3@example.com",
    name: "Charlie Brown",
    role: "Author",
    action: "Created",
  },
  {
    link: "/images/avatar2.png",
    time: "2025-09-07T12:45:00Z",
    src: "user4@example.com",
    name: "Dana Lee",
    role: "Admin",
    action: "Approved",
  },
  {
    link: "/images/avatar1.png",
    time: "2025-09-05T13:00:00Z",
    src: "user5@example.com",
    name: "Eve Wilson",
    role: "Editor",
    action: "Edited",
  },
  {
    link: "/images/avatar2.png",
    time: "2025-09-01T13:15:00Z",
    src: "user6@example.com",
    name: "Frank Davis",
    role: "Reviewer",
    action: "Commented",
  },
  {
    link: "/images/avatar3.png",
    time: "2025-03-08T13:30:00Z",
    src: "user7@example.com",
    name: "Grace Kim",
    role: "Author",
    action: "Drafted",
  },
  {
    link: "/images/avatar1.png",
    time: "2024-09-08T13:45:00Z",
    src: "user8@example.com",
    name: "Hank Taylor",
    role: "Admin",
    action: "Deleted",
  },
  {
    link: "/images/avatar4.png",
    time: "2025-09-08T14:00:00Z",
    src: "user9@example.com",
    name: "Ivy Clark",
    role: "Editor",
    action: "Updated",
  },
  {
    link: "/images/avatar5.png",
    time: "2025-09-08T14:15:00Z",
    src: "user10@example.com",
    name: "Jack Moore",
    role: "Reviewer",
    action: "Scheduled",
  },
];

const profileData = [
  {
    keys: ["Profession", "Downloads"],
    values: ["Student", "500"],
  },
  {
    keys: ["Education", "Experience"],
    values: ["B.Sc. Computer Science", "5 years"],
  },
  {
    keys: ["Skills", "Hobbies"],
    values: ["Music Production, Coding", "Gaming, Traveling"],
  },
  {
    keys: ["Website", "Email"],
    values: ["https://myportfolio.com", "user@example.com"],
  },
  {
    keys: ["Uploads", "Availability"],
    values: ["328", "Freelance"],
  },
];

const quickLinks = [
  { name: "Dashboard", href: "/dashboard" },
  { name: "Upload PDF", href: "/dashboard/upload" },
  { name: "Events", href: "/events" },
  { name: "Study Groups", href: "/groups" },
  { name: "Dashboard", href: "/dashboard" },
  { name: "Upload PDF", href: "/upload" },
];

const support = [
  { name: "About", href: "/about" },
  { name: "Contact ", href: "/contact" },
  { name: "Privacy Policy", href: "/privacy" },
  { name: "Contact ", href: "/contact" },
  { name: "Terms of user", href: "/terms" },
  { name: "vents", href: "/event" },
];


export {
  mockPDFs,
  profileData,
  user,
  badgeColor,
  mockPDF,
  chartData,
  feedDataSet,
  feedData,
  quickLinks,
  support
};
